spring:
  application:
    name: namul
  profiles:
    active: local
  data:
    mongodb:
      host: ${MONGO_HOST}
      port: ${MONGO_PORT}
      database: ${MONGO_DB_NAME}
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}

server:
  forward-headers-strategy: framework
  use-forward-headers: true
  port: ${PORT:8080}