spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/namul}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
  
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: false

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    com.junction.namul: info
    root: warn